spring:
  h2:
    console:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: create


  datasource:
    url: jdbc:h2:mem:testdb
    username: user
    password:
    driver-class-name: org.h2.Driver